language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GCfTZxoqpp1tMmslM5MTI13BLv+bvFhZUuhX+dQFbcVYODQKUjnUj9EBF10PJSTpYqm3GnGpxEoQ6RAUVxlH7rBQUFm4czaZPPgCDSZT3B8pszmQkl1aRyvdmXFoKfyNhFUwBUSsoBpM92wp/UrgIZ/CI0jLoIZbCwn4KH02rf8=
  file:
    - 'remark.js'
    - 'remark.min.js'
  on:
    tags: true
